[package]
name = "solar-system"
version = "0.1.0"
authors = ["Sebastian Rodríguez Colina <srcolinas@gmail.com>"]
edition = "2024"
license = "MIT"
rust-version = "1.85"
publish = false

[dependencies]
eframe = "0.32.0"
egui_extras = "0.32.0"
env_logger = "0.11.8"

